# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(404, 329)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.first_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono L")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        self.first_label.setFont(font)
        self.first_label.setObjectName("first_label")
        self.horizontalLayout.addWidget(self.first_label)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lsecond_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono L")
        font.setPointSize(11)
        font.setBold(True)
        self.lsecond_label.setFont(font)
        self.lsecond_label.setObjectName("lsecond_label")
        self.horizontalLayout_2.addWidget(self.lsecond_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_plus = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Nimbus Mono L")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.btn_plus.setFont(font)
        self.btn_plus.setObjectName("btn_plus")
        self.horizontalLayout_3.addWidget(self.btn_plus)
        self.btn_minus = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.btn_minus.setFont(font)
        self.btn_minus.setObjectName("btn_minus")
        self.horizontalLayout_3.addWidget(self.btn_minus)
        self.btn_mult = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.btn_mult.setFont(font)
        self.btn_mult.setObjectName("btn_mult")
        self.horizontalLayout_3.addWidget(self.btn_mult)
        self.btn_div = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.btn_div.setFont(font)
        self.btn_div.setObjectName("btn_div")
        self.horizontalLayout_3.addWidget(self.btn_div)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.result_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK TC")
        font.setPointSize(16)
        self.result_label.setFont(font)
        self.result_label.setStyleSheet("QLabel {\n"
"color:green\n"
"\n"
"}")
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.verticalLayout.addWidget(self.result_label)

        self.btn_plus.clicked.connect(self.plus_click)
        self.btn_minus.clicked.connect(self.minus_click)
        self.btn_mult.clicked.connect(self.mult_click)
        self.btn_div.clicked.connect(self.div_click)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def plus_click(self):
        first_number = float(self.lineEdit.text())
        second_number = float(self.lineEdit_2.text())
        self.result_label.setText("Addition: {0}".format(first_number + second_number))

    def minus_click(self):
        first_number = float(self.lineEdit.text())
        second_number = float(self.lineEdit_2.text())
        self.result_label.setText("Minus: {0}".format(first_number - second_number))

    def mult_click(self):
        first_number = float(self.lineEdit.text())
        second_number = float(self.lineEdit_2.text())
        self.result_label.setText("Mult: {0}".format(first_number * second_number))

    def div_click(self):
        first_number = float(self.lineEdit.text())
        second_number = float(self.lineEdit_2.text())
        self.result_label.setText("Divide: {0}".format(first_number / second_number))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.first_label.setText(_translate("Form", "First Number"))
        self.lsecond_label.setText(_translate("Form", "Second Number"))
        self.btn_plus.setText(_translate("Form", "+"))
        self.btn_minus.setText(_translate("Form", "-"))
        self.btn_mult.setText(_translate("Form", "*"))
        self.btn_div.setText(_translate("Form", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
