# Form implementation generated from reading ui file 'ui/rp_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from typing import Callable, Union
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIntValidator
from PyQt6.QtWidgets import QDialog, QLabel, QLineEdit, QDialogButtonBox, QVBoxLayout, QHBoxLayout
from model_data.model import Rp


class RpDialog(QDialog):

    def __init__(self, on_save: Callable = None, data: Rp = None):
        super(RpDialog, self).__init__()
        self.edit_org = None
        self.edit_name = None
        self.edit_id = None
        self.on_save = on_save
        self.initialize_ui()
        if data:
            self.data = data
            self.edit_id.setText(str(data.id))
            self.edit_name.setText(data.name)
            self.edit_org.setText(data.full_name)

    def initialize_ui(self):
        self.setWindowTitle("Раздел персонала")
        self.resize(450, 135)
        vbox1 = QVBoxLayout()
        vbox2 = QVBoxLayout()
        vbox3 = QVBoxLayout()
        hbox = QHBoxLayout()
        q_btn = QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel
        button_box = QDialogButtonBox(q_btn)
        button_box.setGeometry(QtCore.QRect(120, 100, 171, 31))
        button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        button_box.accepted.connect(self.save)
        button_box.rejected.connect(self.reject)

        label_id = QtWidgets.QLabel("Идентификатор:")
        label_id.setGeometry(QtCore.QRect(20, 10, 58, 16))
        label_name = QtWidgets.QLabel("Наименование:")
        label_name.setGeometry(QtCore.QRect(20, 40, 54, 16))
        label_org = QtWidgets.QLabel("Организация:")
        label_org.setGeometry(QtCore.QRect(20, 70, 48, 16))
        self.edit_id = QLineEdit()
        self.edit_id.setGeometry(QtCore.QRect(90, 10, 97, 19))
        self.edit_id.setValidator(QIntValidator(1, 1000))
        self.edit_name = QLineEdit()
        self.edit_name.setGeometry(QtCore.QRect(90, 40, 201, 19))
        self.edit_org = QtWidgets.QLineEdit()
        self.edit_org.setGeometry(QtCore.QRect(90, 70, 201, 19))
        vbox1.addWidget(label_id)
        vbox1.addWidget(label_name)
        vbox1.addWidget(label_org)

        vbox2.addWidget(self.edit_id)
        vbox2.addWidget(self.edit_name)
        vbox2.addWidget(self.edit_org)
        hbox.addLayout(vbox1)
        hbox.addLayout(vbox2)
        vbox3.addLayout(hbox)
        vbox3.addWidget(button_box)
        self.setLayout(vbox3)

    def save(self):
        data = Rp(int(self.edit_id.text()), self.edit_name.text(), self.edit_org.text())
        if self.data:
            self.data.id = data.id
            self.data.name = data.name
            self.data.full_name = data.full_name
        if self.on_save:
            self.on_save(data=data)
        self.accept()

